# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/digilent-xdc-master/Arty-A7-35-Master.xdc

# IP: ip/debouncer_0/debouncer_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==debouncer_0 || ORIG_REF_NAME==debouncer_0} -quiet] -quiet
