# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Darius/Desktop/coding_stuff/projects_for_resume/SpectrumAnalyzer/Vivado/DFT_TEST_2/DFT_TEST_2.srcs/sources_1/ip/dft_0/dft_0.xci
# IP: The module: 'dft_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Darius/Desktop/coding_stuff/projects_for_resume/SpectrumAnalyzer/Vivado/DFT_TEST_2/DFT_TEST_2.gen/sources_1/ip/dft_0/dft_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dft_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/Darius/Desktop/coding_stuff/projects_for_resume/SpectrumAnalyzer/Vivado/DFT_TEST_2/DFT_TEST_2.srcs/sources_1/ip/dft_0/dft_0.xci
# IP: The module: 'dft_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Darius/Desktop/coding_stuff/projects_for_resume/SpectrumAnalyzer/Vivado/DFT_TEST_2/DFT_TEST_2.gen/sources_1/ip/dft_0/dft_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dft_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
